#include <opencv2/opencv.hpp>
//#include <opencv2/imgcodecs/imgcodecs.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <raspicam/raspicam_cv.h>
#include <iostream>
#include <vector>
#include <tuple>
#include <signal.h>
#include <tgmath.h>
#include <stdint.h>
#include <sstream>
