## Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile
#

ARDUINO_DIR = /home/schwager/bin/arduino-1.6.4
BOARD_SUB = atmega1284p
CFLAGS_STD = -g -I /home/schwager/sketchbook/hardware/mighty-1284p-master/variants/standard
CXXFLAGS_STD = -g -I /home/schwager/sketchbook/hardware/mighty-1284p-master/variants/standard
#  

ISP_PROG = usbasp
# from boards.txt
BOARD_TAG = mighty_opt
ALTERNATE_CORE = mighty-1284p-master
# This is set in the boards.txt file.
#F_CPU = 16000000L

include /usr/share/arduino/Arduino.mk
